Generating random data and Testing the model on a basic ML Process

f(x,z) = 13*xs + 7*zs - 12

In [46]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D


# Generating random inputs

In [47]:
observation = 1000


In [48]:
xs = np.random.uniform(-10, 10, size=(observation, 1))
zs = np.random.uniform(-10, 10, size = (observation,1))

In [49]:
inputs = np.column_stack((xs,zs))

In [50]:
print(inputs.shape)

(1000, 2)


In [51]:
noise = np.random.uniform(-1, 1, (observation,1))

In [52]:
targets = 13*xs + 7*zs - 12 + noise

In [53]:
print(targets)
print(targets.shape)

[[ 1.01738919e+00]
 [-1.96207337e+01]
 [ 6.70998330e+01]
 [ 8.29640293e+01]
 [-1.68696775e+01]
 [ 7.04283793e+01]
 [ 1.31150936e+02]
 [-7.34935133e+01]
 [-1.68726719e+02]
 [ 1.17090848e+02]
 [-4.82576103e+00]
 [-1.22861310e+01]
 [-2.87171556e+01]
 [ 1.50580072e-01]
 [-9.24288559e+01]
 [ 7.38615554e+01]
 [-3.56703183e+01]
 [ 1.16112838e+01]
 [-7.67849178e+01]
 [ 9.32703400e+00]
 [ 1.34153644e+01]
 [-2.27869898e+01]
 [ 7.35150839e+01]
 [ 2.91647894e+01]
 [-1.29783066e+02]
 [ 1.58062483e+02]
 [ 1.35166767e+02]
 [-1.76091184e+02]
 [ 9.67993388e+00]
 [ 3.22006164e+01]
 [-1.22582060e+02]
 [ 3.26220980e+01]
 [-1.65191967e+02]
 [-1.25687613e+02]
 [-8.65639261e+00]
 [ 6.64994450e+01]
 [ 2.69900766e+01]
 [-6.06368666e+01]
 [ 5.30674412e+00]
 [ 1.48854980e+02]
 [-1.08165924e+02]
 [ 1.07151769e+02]
 [-1.13664608e+02]
 [-9.59089228e+01]
 [ 2.33844478e+01]
 [ 4.00167856e+01]
 [-1.53378642e+02]
 [ 9.79492225e+01]
 [ 1.54728074e+02]
 [-1.97458704e+02]
 [-4.36212581e+01]
 [ 4.80016658e+01]
 [-2.1169792

In [54]:
init_range = 0.1
weights = np.random.uniform(low=-init_range, high=init_range, size=(2, 1))
biases = np.random.uniform(low=-init_range, high=init_range, size=1)

print (weights)
print (biases)

[[ 0.02862128]
 [-0.06353037]]
[0.09253868]


In [55]:
eta=0.05

In [56]:

# optimization algorithm
# gradient descent

for i in range(200):
    
    outputs = np.dot(inputs, weights) + biases
    
    deltas = outputs - targets
    
    loss = (np.sum(targets - outputs)**2)/2 / observation
    delta_scaled = deltas/observation
    weights = weights - eta * np.dot(inputs.T, delta_scaled)
    biases = biases - eta * np.sum(delta_scaled)
    
    print (loss)
    

29446.458953862293
104958.91341111006
41654.472860930415
68155.22511585419
41810.35459871352
49602.425959939406
37261.067192015755
38276.45813922302
31627.6725500086
30391.431195622274
26276.30298801748
24462.455938763414
21616.983321224616
19819.175381411816
17701.853148490867
16107.935980548442
14463.635066144381
13111.829561040278
11804.929808825374
10681.164027557586
9629.720279114705
8704.442829713065
7853.161910532032
7094.939840392447
6403.450908811302
5783.631635250758
5220.975912691343
4714.934420783212
4256.694607283648
3843.818911258611
3470.4386532651515
3133.6948645450075
2829.38125470827
2554.7828829133105
2306.7259268799558
2082.826926943618
1880.6116715936932
1698.061431767115
1533.2094889236039
1384.3763539815775
1249.9811259663152
1128.639521262139
1019.0727430854652
920.1454919873604
830.8197114095267
750.1668071427762
677.3425047105426
611.588394539108
552.21707271205
498.60962227267976
450.2060312811713
406.5014418788727
367.0394764942232
331.40841670583313
299.236

In [57]:
print (weights, biases)


[[13.00294325]
 [ 6.99849467]] [-12.01270451]
